// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27nVr6lKWiTgj0lW0wQx5m1-lslhMipw',
    appId: '1:267118373830:web:dbec72cb78e58940fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    authDomain: 'fans-food-stf.firebaseapp.com',
    storageBucket: 'fans-food-stf.firebasestorage.app',
    measurementId: 'G-0J0Q8GCTX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0dB043MPcJDKDqq_Uf-jJUuQK2mjXiI',
    appId: '1:267118373830:android:1e13941e64d5bbc1fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    storageBucket: 'fans-food-stf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvPXXbqn-E6J91XrecuWXK9eJn9r4_Q8',
    appId: '1:267118373830:ios:d20d15b84eac95f1fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    storageBucket: 'fans-food-stf.firebasestorage.app',
    iosBundleId: 'com.fansfood.fansFoodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvPXXbqn-E6J91XrecuWXK9eJn9r4_Q8',
    appId: '1:267118373830:ios:d20d15b84eac95f1fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    storageBucket: 'fans-food-stf.firebasestorage.app',
    iosBundleId: 'com.fansfood.fansFoodOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB27nVr6lKWiTgj0lW0wQx5m1-lslhMipw',
    appId: '1:267118373830:web:aada3c0ed10e2973fc60c7',
    messagingSenderId: '267118373830',
    projectId: 'fans-food-stf',
    authDomain: 'fans-food-stf.firebaseapp.com',
    storageBucket: 'fans-food-stf.firebasestorage.app',
    measurementId: 'G-NCXFE88972',
  );
}
